add name for every referee
Pavel-Demidyuk/ref7 pull request #13
Opened 2020-03-26 18:22 UTC by MishaKulik

Replacing id with name, because name is more readable and easy.

2020-03-28 11:32 UTC, Pavel-Demidyuk approved these changes

2020-03-28 11:32 UTC, Pavel-Demidyuk commented on components/RefereeStatus.js
> +    firebase
please move this code to the database controller

2020-03-28 11:32 UTC, Pavel-Demidyuk commented on components/RefereeStatus.js
> +    firebase
final result: db.getCompetetions()

2020-03-28 11:32 UTC, Pavel-Demidyuk commented on components/RefereeStatus.js
> +            <Cell data={global.name} textStyle={{ margin: 2, color: '#000' }} />
rendering should not start before the db call is finished

2020-03-28 11:32 UTC, Pavel-Demidyuk commented on db/init.js
> +    global.pinPin = pin;
is there a better way to get pin of the competition?

2020-04-04 12:29 UTC, pdemidyuk-ib commented on db/ref.js
> +import * as firebase from 'firebase';
please remove firebase import here

2020-04-10 07:43 UTC, max8rr8 requested changes

2020-04-10 07:43 UTC, maximmasterr commented on screens/TimerScreen.js
> +                    Your name: {random_name({ seed:extractID(Constants.deviceId), first: true })}{' '}
Not optimal code will slow render, because name is generated on each render

2020-04-10 07:43 UTC, maximmasterr commented on db/ref.js
> +
Replace get name with hook 
```javascript
function useName(id){
  let [name, setName] = useState(0)
  useEffect(()=>{
    function c(snapshot) {
      setName(name.val())
    }
    let n = global.connection.child('ref').child(id).child('name')
    n.on('value', c)
    return ()=>n.off('value', c)
  }, [id])
  return name
}
```

2020-04-10 07:43 UTC, maximmasterr commented on components/RefereeStatus.js
> +    const [name, setName] = useState();
Replace with
```js
const name = useName(id)
```

2020-04-10 07:43 UTC, maximmasterr commented on db/ref.js
> +        session: 1
Where do we need session

2020-04-10 07:43 UTC, maximmasterr commented on package.json
> +    "react-useinterval": "^1.0.1"
Do we use react-useinterval? If not remove it from our packages

2020-04-10 07:43 UTC, maximmasterr commented on screens/TimerScreen.js
> +
We dont use session any where

2020-04-10 07:43 UTC, maximmasterr commented on screens/TimerScreen.js
> +
Add more optimal ode here
```js
const [name, setName] = useState("")
useEffect(()=>{
  setName = random_name({ seed:extractID(Constants.deviceId), first: true })
}, [])
```

2020-04-10 07:43 UTC, maximmasterr commented on screens/TimerScreen.js
> +                    Your name: {random_name({ seed:extractID(Constants.deviceId), first: true })}{' '}
Look comment above and replace `random_name({ seed:extractID(Constants.deviceId), first: true })` with `name`

2020-04-11 11:46 UTC, closed without merging